server:
  port: 8085

management:
  endpoint:
    health:
      probes:
        enabled: true

keycloak:
  server-url: http://localhost:8088
  admin-username: admin
  admin-password: password
  
---
server:
  port: 8085

management:
  endpoint:
    health:     
      probes:
        enabled: true

spring:
  config:
    activate:
      on-profile: avib  

keycloak:
  server-url: http://gsdpi-keycloak:80
  admin-username: admin
  admin-password: password   