server:
  port: 8084

management:
  endpoint:
    health:
      probes:
        enabled: true

keycloak:
  realm: avib
  resource: admin-api
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  use-resource-role-mappings: true

---
server:
  port: 8084

management:
  endpoint:
    health:     
      probes:
        enabled: true
          
spring:
  config:
    activate:
      on-profile: avib
      
keycloak:
  realm: avib
  resource: admin-api
  auth-server-url: http://avib-keycloak:8080/auth
  ssl-required: external
  use-resource-role-mappings: true         