server:
  port: 8084

management:
  endpoint:
    health:
      probes:
        enabled: true

---
server:
  port: 8084

management:
  endpoint:
    health:     
      probes:
        enabled: true
          
spring:
  config:
    activate:
      on-profile: avib     