server:
  port: 8085

keycloak:
  server-url: http://localhost:8088/auth
  admin-username: admin
  admin-password: password
  
---
server:
  port: 8085

spring:
  config:
    activate:
      on-profile: avib  

keycloak:
  server-url: http://avib-keycloak:8080/auth
  admin-username: admin
  admin-password: password   